/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


--Find total customers by countries
select country,count(customer_key) as total_customer
from gold.dim_customers
group by country
order by total_customer desc

--Find total customers by Gender
select gender,count(customer_key) as total_customer
from gold.dim_customers
group by gender
order by total_customer desc

-- Find total product by categort
select category,count(product_key) as Total_product
from gold.dim_products
group by category
order by Total_product desc

-- What is the average cost in each category
select category,avg(cost) as Average_cost
from gold.dim_products
group by category
order by Average_cost desc

--What is the total revenue generated by each category
select p.category,sum(s.sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_products p
on p.product_key=s.product_key
group by p.category
order by total_revenue desc

-- Find total revenue is generated by each customer
select c.customer_key,c.first_name,c.last_name,sum(s.sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc
 
--What is the distribution of sold item across countries
select c.country,sum(s.quantity) total_sold_item
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by c.country
order by total_sold_item desc
  
